pyuic6 src/UtcTool2d/selectImage.ui -o src/UtcTool2d/selectImage_ui.py
pyuic6 src/UtcTool2d/loadingScreen.ui -o src/UtcTool2d/loadingScreen_ui.py
pyuic6 src/UtcTool2d/windowsTooLarge.ui -o src/UtcTool2d/windowsTooLarge_ui.py
pyuic6 src/UtcTool2d/saveRoi.ui -o src/UtcTool2d/saveRoi_ui.py
pyuic6 src/UtcTool2d/roiSelection.ui -o src/UtcTool2d/roiSelection_ui.py
pyuic6 src/UtcTool2d/rfAnalysis.ui -o src/UtcTool2d/rfAnalysis_ui.py
pyuic6 src/UtcTool2d/loadRoi.ui -o src/UtcTool2d/loadRoi_ui.py
pyuic6 src/UtcTool2d/exportData.ui -o src/UtcTool2d/exportData_ui.py
pyuic6 src/UtcTool2d/editImageDisplay.ui -o src/UtcTool2d/editImageDisplay_ui.py
pyuic6 src/UtcTool2d/analysisParamsSelection.ui -o src/UtcTool2d/analysisParamsSelection_ui.py
pyuic6 src/UtcTool2d/psGraphDisplay.ui -o src/UtcTool2d/psGraphDisplay_ui.py
pyuic6 src/UtcTool2d/saveConfig.ui -o src/UtcTool2d/saveConfig_ui.py
pyuic6 src/UtcTool2d/loadConfig.ui -o src/UtcTool2d/loadConfig_ui.py
